import numpy as np
import trimesh
from shapely.geometry import Polygon
from shapely.ops import unary_union
from collections import defaultdict

from .hashing import precompute_plane_drawers
from .geometry import get_projection_axes, project_to_plane_with_axes, remesh_shapely_polygon
from .utils import snap_and_clean_mesh
from .coplanarmesh import clean_mesh_and_reindex

def patch_single_mesh(mesh, regions, face_ids_to_remove, is_mesh_b=False, digits_vertex=5):
    """
    Hollows out old coplanar facets from a mesh and patches them with newly triangulated boolean pieces.

    This function acts as the final assembly assembly line, sewing geometric sub-regions
    (`PERFECT`, `PARTIAL_SHARED`, etc.) back onto the parent mesh shell while maintaining
    an operational tracking mask of newly formed coplanar regions.

    Args:
        mesh (trimesh.Trimesh): The base mesh to be updated.
        regions (list): Boolean region descriptors generated by the intersection analyzer.
        face_ids_to_remove (list): Face indices destined for deletion due to overlap slicing.
        is_mesh_b (bool): Set to True if processing the secondary colliding body (Mesh B).
        digits_vertex (int): Decimal precision used for collapsing coincident boundary vertices.

    Returns:
        tuple: `(cleaned_mesh, actual_overlap_indices)` where cleaned_mesh is a trimesh.Trimesh
               and actual_overlap_indices contains the re-indexed face IDs belonging to the contact zone.
    """
    new_mesh = mesh.copy()
    isolated_patch_verts = []
    isolated_patch_tris = []
    current_vertex_offset = len(new_mesh.vertices)
    overlap_patch_flags = []

    # Map sub-regions back from 2D coordinates to 3D space
    for match_type, data in regions:
        is_overlap_zone = (match_type in ["PERFECT", "PARTIAL_SHARED"])
        if match_type == "PERFECT":
            if not is_mesh_b:
                continue
            triA_verts, dir_sign = data
            verts3d = triA_verts.copy()
            tris = np.array([[0, 1, 2]], dtype=np.int32)
            if dir_sign == -1.0:
                tris = tris[:, [0, 2, 1]]
        elif match_type == "PARTIAL_SHARED":
            verts2d, tris, n, d, x, y, dir_sign = data
            tris = tris.copy()
            origin = -d * n
            verts3d = verts2d[:, 0][:, None] * x + verts2d[:, 1][:, None] * y + origin
            if is_mesh_b and dir_sign == -1.0:
                tris = tris[:, [0, 2, 1]]
        elif match_type == "PARTIAL_REMAIN_A":
            if is_mesh_b:
                continue
            verts2d, tris, n, d, x, y = data
            tris = tris.copy()
            origin = -d * n
            verts3d = verts2d[:, 0][:, None] * x + verts2d[:, 1][:, None] * y + origin
        elif match_type == "PARTIAL_REMAIN_B":
            if not is_mesh_b:
                continue
            verts2d, tris, n, d, x, y, dir_sign = data
            tris = tris.copy()
            origin = -d * n
            verts3d = verts2d[:, 0][:, None] * x + verts2d[:, 1][:, None] * y + origin
            if dir_sign == -1.0:
                tris = tris[:, [0, 2, 1]]

        overlap_patch_flags.append((len(tris), is_overlap_zone))
        isolated_patch_verts.append(verts3d)
        isolated_patch_tris.append(tris + current_vertex_offset)
        current_vertex_offset += len(verts3d)

    # Perform hollowing operation on the original shell mesh
    mask = np.ones(len(new_mesh.faces), dtype=bool)
    mask[face_ids_to_remove] = False
    hollow_mesh = trimesh.Trimesh(vertices=new_mesh.vertices, faces=new_mesh.faces[mask], process=False)
    hollow_mesh.merge_vertices(merge_tex=False, merge_norm=False, digits_vertex=digits_vertex)
    hollow_mesh.remove_unreferenced_vertices()
    hollow_faces_count = len(hollow_mesh.faces)

    # Reassemble the hollow shell with the new 3D patch elements
    if isolated_patch_verts:
        final_vertices = np.vstack([hollow_mesh.vertices] + isolated_patch_verts)
        patch_offset = len(hollow_mesh.vertices) - len(new_mesh.vertices)
        shifted_tris = [t + patch_offset for t in isolated_patch_tris]
        final_faces = np.vstack([hollow_mesh.faces] + shifted_tris)
        cleaned_mesh = trimesh.Trimesh(vertices=final_vertices, faces=final_faces, process=False)
    else:
        cleaned_mesh = hollow_mesh

    # Construct and track the active tracking indices belonging to the contact zones
    patch_overlap_face_indices = []
    face_cursor = hollow_faces_count
    for tri_count, is_overlap in overlap_patch_flags:
        if is_overlap:
            patch_overlap_face_indices.extend(range(face_cursor, face_cursor + tri_count))
        face_cursor += tri_count

    overlap_mask_temp = np.zeros(len(cleaned_mesh.faces), dtype=bool)
    overlap_mask_temp[patch_overlap_face_indices] = True
    cleaned_mesh.metadata['overlap_mask_temp'] = overlap_mask_temp

    # Re-weld all boundary junctions to achieve geometric continuity
    old_faces_count = len(cleaned_mesh.faces)
    face_ids = np.arange(old_faces_count)
    cleaned_mesh.metadata['face_ids'] = face_ids
    cleaned_mesh.merge_vertices(merge_tex=False, merge_norm=False, digits_vertex=digits_vertex)
    cleaned_mesh.vertex_normals

    # Retrieve survivors after index re-mapping shifts
    survived_mask = cleaned_mesh.metadata['overlap_mask_temp'][cleaned_mesh.metadata['face_ids']]
    actual_overlap_indices = np.where(survived_mask)[0]
    return cleaned_mesh, list(actual_overlap_indices)

def extract_coplanar_overlap_pure_id(meshA, meshB, eps=1e-3):
    """
    Analyzes two meshes to extract boolean intersecting regions on common plane channels.

    Acts as the core topological analyzer engine. It buckets faces into shared planes,
    projects them to 2D viewports, and runs strict 2D constructive solid geometry (CSG)
    operations to output precise sliced fragments.

    Args:
        meshA (trimesh.Trimesh): Primary source mesh (Mesh A).
        meshB (trimesh.Trimesh): Secondary source mesh (Mesh B).
        eps (float): Intersect distance threshold buffer for spatial comparisons.

    Returns:
        tuple: `(regions, removeA, removeB, overlap_A_perfect, coplanar_pairs)`
               outlining slicing topologies and lists of face IDs slated for removal.
    """
    regions = []
    removeA, removeB = set(), set()
    overlap_A_perfect = []
    coplanar_pairs = []

    # Initialize RTree spatial indexing structures and fuzzy plane drawer maps
    drawersA = precompute_plane_drawers(meshA)
    drawersB = precompute_plane_drawers(meshB)
    b_rtree = meshB.triangles_tree
    common_plane_keys = set(drawersA.keys()).intersection(set(drawersB.keys()))

    # Process each shared plane cluster individually
    for key in common_plane_keys:
        face_ids_A = drawersA[key]
        face_ids_B_all = set([item[0] for item in drawersB[key]])
        b_face_to_normal = {item[0]: item[1] for item in drawersB[key]}
        if not face_ids_A or not face_ids_B_all:
            continue

        # Establish 2D projection viewports for the current plane grouping
        _, n_ref, _ = face_ids_A[0]
        x, y = get_projection_axes(n_ref)
        b_face_bitten_by_A = defaultdict(list)
        b_face_meta = {}

        # Loop through faces in Mesh A to calculate intersection impacts on Mesh B elements
        for i, nA, dA in face_ids_A:
            triA_verts = meshA.vertices[meshA.faces[i]]
            bounds_min = triA_verts.min(axis=0) - eps
            bounds_max = triA_verts.max(axis=0) + eps
            nearby_B_ids = b_rtree.intersection(np.hstack([bounds_min, bounds_max]))
            valid_B_ids = [j for j in nearby_B_ids if j in face_ids_B_all]
            if not valid_B_ids:
                continue

            polyA_raw = Polygon(project_to_plane_with_axes(triA_verts, x, y))
            if polyA_raw.area < eps:
                continue

            b_intersections_this_A = []
            matched_b_ids_this_A = []
            polyB_list_this_A = []

            for j in valid_B_ids:
                nB = b_face_to_normal[j]
                triB_verts = meshB.vertices[meshB.faces[j]]
                polyB_raw = Polygon(project_to_plane_with_axes(triB_verts, x, y))
                dir_sign = 1.0 if np.dot(nA, nB) > 0 else -1.0

                if polyA_raw.buffer(eps).intersects(polyB_raw.buffer(eps)):
                    inter_s = polyA_raw.buffer(eps).intersection(polyB_raw.buffer(eps))
                    if not inter_s.is_empty and inter_s.area > eps:
                        b_intersections_this_A.append(inter_s)
                        matched_b_ids_this_A.append(j)
                        polyB_list_this_A.append((j, polyB_raw, nB, dir_sign, triB_verts))
                        coplanar_pairs.append((i, j))
                        b_face_bitten_by_A[j].append(inter_s)
                        if j not in b_face_meta:
                            b_face_meta[j] = (polyB_raw, nB, dir_sign, triB_verts)

            if not b_intersections_this_A:
                continue

            total_b_zone = unary_union(b_intersections_this_A).buffer(0)
            final_inter_zone = polyA_raw.intersection(total_b_zone)
            if final_inter_zone.is_empty or final_inter_zone.area < eps:
                continue

            area_triA = polyA_raw.area
            area_triB_total = sum(pB.area for _, pB, _, _, _ in polyB_list_this_A)

            # State 1: Perfect match configuration (No remeshing required for this entry)
            if final_inter_zone.area >= area_triA * (1 - eps) and final_inter_zone.area >= area_triB_total * (1 - eps):
                overlap_A_perfect.append(i)
                for j in matched_b_ids_this_A:
                    removeB.add(j)
                    if j in b_face_bitten_by_A:
                        del b_face_bitten_by_A[j]
                regions.append(("PERFECT", (triA_verts, polyB_list_this_A[0][3])))
                continue

            # Queue up current source index configurations for hollowing deletion passes
            removeA.add(i)
            for j in matched_b_ids_this_A:
                removeB.add(j)

            # State 2: Segment out partial overlapping zones
            geoms_inter = [final_inter_zone] if final_inter_zone.geom_type == "Polygon" else list(final_inter_zone.geoms)
            for g in geoms_inter:
                if g.area > eps:
                    v2d, t2d = remesh_shapely_polygon(g)
                    if v2d is not None:
                        regions.append(("PARTIAL_SHARED", (v2d, t2d, nA, dA, x, y, polyB_list_this_A[0][3])))

            # State 3: Segment out remainder chunks for Mesh A
            final_remain_A = polyA_raw.difference(total_b_zone)
            if not final_remain_A.is_empty and final_remain_A.area > eps:
                geoms_remA = [final_remain_A] if final_remain_A.geom_type == "Polygon" else list(final_remain_A.geoms)
                for g in geoms_remA:
                    if g.geom_type == "Polygon" and g.area > eps:
                        v2d, t2d = remesh_shapely_polygon(g)
                        if v2d is not None:
                            regions.append(("PARTIAL_REMAIN_A", (v2d, t2d, nA, dA, x, y)))

        # State 4: Segment out remainder chunks for Mesh B
        for j, bites in b_face_bitten_by_A.items():
            polyB_raw, nB, dir_sign, triB_verts = b_face_meta[j]
            combined_A_bites_on_this_B = unary_union(bites).buffer(eps * 0.1).buffer(-eps * 0.1)
            final_remain_B = polyB_raw.difference(combined_A_bites_on_this_B.buffer(1e-6))

            if not final_remain_B.is_empty and final_remain_B.area > eps:
                if final_remain_B.geom_type == "MultiPolygon":
                    polys_to_process = list(final_remain_B.geoms)
                elif final_remain_B.geom_type == "Polygon":
                    polys_to_process = [final_remain_B]
                else:
                    polys_to_process = [g for g in final_remain_B.geoms if g.geom_type == "Polygon"]

                for g in polys_to_process:
                    if g.area > eps:
                        v2d, t2d = remesh_shapely_polygon(g)
                        if v2d is not None:
                            dB = -np.dot(nB, triB_verts[0])
                            regions.append(("PARTIAL_REMAIN_B", (v2d, t2d, nB, dB, x, y, dir_sign)))

    return regions, list(removeA), list(removeB), overlap_A_perfect, sorted(list(set(coplanar_pairs)))

def process_and_label_coplanar(meshA, meshB, eps=1e-4, grid_size=1e-5, digits_vertex=5):
    """
    Orchestrates the entry-level pairwise execution loop for the slicing state machine.

    Args:
        meshA (trimesh.Trimesh): Input mesh framework A.
        meshB (trimesh.Trimesh): Input mesh framework B.
        eps (float): Precision tolerance buffer for boolean intersections.
        grid_size (float): Dimension quantization size for pre-processing vertex snap steps.
        digits_vertex (int): Rounded precision length passed to downstream stitching engines.

    Returns:
        tuple: `(meshA_clean, meshB_clean, overlap_A_idx, overlap_B_idx, raw_pairs)`.
    """
    # Sanitize inputs to prevent floating point noise from altering geometric boundary states
    meshA_sanitized = snap_and_clean_mesh(meshA, grid_size=grid_size)
    meshB_sanitized = snap_and_clean_mesh(meshB, grid_size=grid_size)

    regions, removeA, removeB, overlap_A_perfect, raw_coplanar_pairs = extract_coplanar_overlap_pure_id(
        meshA_sanitized, meshB_sanitized, eps=eps
    )
    if not regions:
        return meshA_sanitized.copy(), meshB_sanitized.copy(), [], [], []

    # Sew the computed boolean layout fragments onto the hollowed out shells
    meshA_clean, overlap_A_partial = patch_single_mesh(meshA_sanitized, regions, removeA, is_mesh_b=False, digits_vertex=digits_vertex)
    meshB_clean, overlap_B = patch_single_mesh(meshB_sanitized, regions, removeB, is_mesh_b=True, digits_vertex=digits_vertex)

    return meshA_clean, meshB_clean, sorted(overlap_A_partial), sorted(overlap_B), raw_coplanar_pairs